### ISSUE TITLE
Paypal - Confirmation page not found

### ISSUE THREAD

**Issue by robsontenorio** [Code-Pop/vue-mastery#150] opened 2018-05-01 02:49 UTC
After login on Paypal with credentials for Sandbox and confirm the activation, the system redirects to a a url with an error message.

https://vue-mastery-staging.firebaseapp.com/pricing/thank-you-monthly

![captura de tela 2018-04-30 as 23 47 18](https://user-images.githubusercontent.com/118955/39459333-fc31bab0-4cd0-11e8-8140-9679aff712e4.png)

When paying with Credit Card the thank you URL is ok.

**Comment by Gregg** [comment] 2018-05-01 03:05
@pieer .. looks like there might be a link mismatch, can you verify?

**Comment by pieer** [comment] 2018-05-03 10:00
I can't reproduce. But maybe that has been fixed with the last bug fix on static pages

**Closed by pieer** 2018-05-03 10:00 UTC
